[package]
name = "container"
version = "0.1.0"
edition = "2021"

[dependencies]
database = { path = "../database" }
services = { path = "../services" }
mongodb = { workspace = true }
workspace-hack = { version = "0.1", path = "../workspace-hack" }
