[workspace]
members = [
    "api",
    "entity-base",   # 你的主项目
    "entity-derive", # 过程宏项目
    "entity-base",
    "rbac",
    "database",
    "entities",
    "task",
    "services", "storage",
]
resolver = "2"
