[package]
name = "entities"
version = "0.1.0"
edition = "2021"

[dependencies]
thiserror = "2.0"
serde = { version = "1.0", features = ["derive"] }
entity-base = { path = "../entity-base" }
entity-derive = { path = "../entity-derive" }
rbac = { path = "../rbac" }
md5 = "0.7.0"
