[package]
name = "services"
version = "0.1.0"
edition = "2021"


[dependencies]
entities = { path = "../entities" }
libs = { path = "../crates/libs" }
thiserror = { workspace = true }
serde = { workspace = true, features = ["derive"] }
async-trait = { workspace = true }
