[package]
name = "storage"
version = "0.1.0"
edition = "2021"

[dependencies]
thiserror = "1.0"
tokio = { version = "1.0", features = ["fs", "io-util"] }

[dev-dependencies]
tempfile = "3.2"
tokio = { version = "1.0", features = ["full"] }
