[package]
name = "rbac"
version = "0.1.0"
edition = "2021"

[dependencies]
async-trait = "0.1"
casbin = { version = "2.5.0", features = ["tokio"] }
mongodb = "3.1.0"
thiserror = "2.0"
tokio = { version = "1.0", features = ["full"] }
serde = { version = "1.0", features = ["derive"] }
