[package]
name = "entity-derive"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
syn = "2.0"
quote = "1.0"
entity-base = { path = "../entity-base" }
workspace-hack = { version = "0.1", path = "../workspace-hack" }
