[app]
port = 10001
secret = "secret"
statistic_host = "http://localhost:3000"
assets_path = "./assets"
upload_path = "./uploads"

[database]
uri = "mongodb://dev:devdev@localhost:27017/?authSource=admin"
db_name = "vietnam-paint"


[services.segment_hair]
url = "http://localhost:8849/segment_hair"
